//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashReportPeople
    {
        public string PersonID { get; set; }
        public string RD_NO { get; set; }
        public string PersonType { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
    
        public virtual CrashReport CrashReport { get; set; }
    }
}
