//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrashReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrashReport()
        {
            this.CrashReportPeoples = new HashSet<CrashReportPeople>();
        }
    
        public string RD_NO { get; set; }
        public Nullable<System.DateTime> CrashDate { get; set; }
        public string PrimeContributingCause { get; set; }
        public string MostSevereInjury { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrashReportPeople> CrashReportPeoples { get; set; }
    }
}
